"""add timestamps to complaints

Revision ID: 1b7ff8ac01a0
Revises: ddda2a5335a3
Create Date: 2026-08-17 14:52:43.924067

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1b7ff8ac01a0'
down_revision: str | Sequence[str] | None = 'ddda2a5335a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('response_timestamp', sa.DateTime(), nullable=True))
    op.add_column('complaints', sa.Column('follow_up_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'follow_up_timestamp')
    op.drop_column('complaints', 'response_timestamp')
    # ### end Alembic commands ###
