"""add_hashed_password_to_invitation

Revision ID: 1f12599dbc4f
Revises: d16ccbae5d5f
Create Date: 2026-08-15 18:01:59.772606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f12599dbc4f'
down_revision: Union[str, Sequence[str], None] = 'd16ccbae5d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_invitations', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_invitations', 'hashed_password')
    # ### end Alembic commands ###
