"""add_otp_fields_to_users

Revision ID: 39db37721a51
Revises: 50419226e7c6
Create Date: 2026-08-15 12:43:07.098216

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39db37721a51"
down_revision: str | Sequence[str] | None = "50419226e7c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("verification_otp", sa.String(length=6), nullable=True)
    )
    op.add_column("users", sa.Column("otp_created_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "otp_created_at")
    op.drop_column("users", "verification_otp")
    # ### end Alembic commands ###
