"""add_is_archived_columns

Revision ID: 40810a7ae7a2
Revises: 1f12599dbc4f
Create Date: 2026-08-15 20:28:06.973006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40810a7ae7a2'
down_revision: Union[str, Sequence[str], None] = '1f12599dbc4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('departments', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_archived', sa.Boolean(), nullable=True))
    
    # Populate existing rows
    op.execute("UPDATE departments SET is_archived = False")
    op.execute("UPDATE users SET is_archived = False")
    
    # Alter column to be NOT NULL
    op.alter_column('departments', 'is_archived', nullable=False)
    op.alter_column('users', 'is_archived', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_archived')
    op.drop_column('departments', 'is_archived')
    # ### end Alembic commands ###
