"""add multi agent fields and customer feedback

Revision ID: 98f40fd7dbf7
Revises: aedc82d5ccbd
Create Date: 2026-08-17 00:14:37.615054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98f40fd7dbf7'
down_revision: Union[str, Sequence[str], None] = 'aedc82d5ccbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint_ai_analysis', sa.Column('solution_high', sa.Text(), nullable=True))
    op.add_column('complaint_ai_analysis', sa.Column('warnings', sa.JSON(), nullable=True))
    op.add_column('complaint_ai_analysis', sa.Column('evidence', sa.JSON(), nullable=True))
    op.add_column('complaint_ai_analysis', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('complaint_ai_analysis', sa.Column('diagnosis', sa.String(length=255), nullable=True))
    op.add_column('complaint_ai_analysis', sa.Column('root_cause', sa.Text(), nullable=True))
    op.add_column('complaint_ai_analysis', sa.Column('risk_level', sa.String(length=50), nullable=True))
    op.add_column('complaint_ai_analysis', sa.Column('policy_status', sa.String(length=50), nullable=True))
    op.add_column('complaint_ai_analysis', sa.Column('final_decision', sa.String(length=100), nullable=True))
    op.add_column('complaint_ai_analysis', sa.Column('critic_feedback', sa.Text(), nullable=True))
    op.add_column('complaint_ai_analysis', sa.Column('reasoning', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('customer_feedback', sa.Boolean(), nullable=True))
    op.alter_column('complaints', 'complaint1',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('complaints', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_complaints_ticket_number'), table_name='complaints')
    op.create_index(op.f('ix_complaints_ticket_number'), 'complaints', ['ticket_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_ticket_number'), table_name='complaints')
    op.create_index(op.f('ix_complaints_ticket_number'), 'complaints', ['ticket_number'], unique=False)
    op.alter_column('complaints', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('complaints', 'complaint1',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('complaints', 'customer_feedback')
    op.drop_column('complaint_ai_analysis', 'reasoning')
    op.drop_column('complaint_ai_analysis', 'critic_feedback')
    op.drop_column('complaint_ai_analysis', 'final_decision')
    op.drop_column('complaint_ai_analysis', 'policy_status')
    op.drop_column('complaint_ai_analysis', 'risk_level')
    op.drop_column('complaint_ai_analysis', 'root_cause')
    op.drop_column('complaint_ai_analysis', 'diagnosis')
    op.drop_column('complaint_ai_analysis', 'confidence_score')
    op.drop_column('complaint_ai_analysis', 'evidence')
    op.drop_column('complaint_ai_analysis', 'warnings')
    op.drop_column('complaint_ai_analysis', 'solution_high')
    # ### end Alembic commands ###
