"""add_client_invitation_and_department

Revision ID: d16ccbae5d5f
Revises: 39db37721a51
Create Date: 2026-08-15 18:01:11.562941

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d16ccbae5d5f"
down_revision: str | Sequence[str] | None = "39db37721a51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_departments_id"), "departments", ["id"], unique=False)
    op.create_index(op.f("ix_departments_name"), "departments", ["name"], unique=True)
    op.create_table(
        "client_invitations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("department_id", sa.String(length=36), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("is_activated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_client_invitations_email"),
        "client_invitations",
        ["email"],
        unique=True,
    )
    op.create_index(
        op.f("ix_client_invitations_id"), "client_invitations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_client_invitations_token"),
        "client_invitations",
        ["token"],
        unique=True,
    )
    op.add_column(
        "users", sa.Column("department_id", sa.String(length=36), nullable=True)
    )
    op.create_foreign_key(
        None, "users", "departments", ["department_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "department_id")
    op.drop_index(op.f("ix_client_invitations_token"), table_name="client_invitations")
    op.drop_index(op.f("ix_client_invitations_id"), table_name="client_invitations")
    op.drop_index(op.f("ix_client_invitations_email"), table_name="client_invitations")
    op.drop_table("client_invitations")
    op.drop_index(op.f("ix_departments_name"), table_name="departments")
    op.drop_index(op.f("ix_departments_id"), table_name="departments")
    op.drop_table("departments")
    # ### end Alembic commands ###
