"""add resolved_by to complaints

Revision ID: ddda2a5335a3
Revises: 98f40fd7dbf7
Create Date: 2026-08-17 13:21:40.748267

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ddda2a5335a3"
down_revision: str | Sequence[str] | None = "98f40fd7dbf7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "complaints", sa.Column("resolved_by", sa.String(length=50), nullable=True)
    )
    op.drop_column("complaints", "received_via")
    op.drop_column("complaints", "state")
    op.drop_column("complaints", "city")
    op.drop_column("complaints", "zip_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "complaints",
        sa.Column("zip_code", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "complaints",
        sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "complaints",
        sa.Column("state", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "complaints",
        sa.Column("received_via", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("complaints", "resolved_by")
    # ### end Alembic commands ###
